// Generated by CoffeeScript 2.5.1
console.log(1 + 2);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYWRhbS5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsiY29mZmVlXFxhZGFtLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsT0FBTyxDQUFDLEdBQVIsQ0FBWSxDQUFBLEdBQUUsQ0FBZCIsInNvdXJjZXNDb250ZW50IjpbImNvbnNvbGUubG9nIDErMiJdfQ==
//# sourceURL=c:\Users\MIXITRIXI\LAB\balls\coffee\adam.coffee